name = "formalization"
version = "0.1.0"
defaultTargets = ["Formalization"]

[lean_options]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "Formalization"
